# Generated by Django 5.1.6 on 2025-02-22 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0007_purchaseapplication_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseapplication',
            name='application_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
